#ifndef _TIMER_CONFIG_H
#define _TIMER_CONFIG_H

//Options : TIMER0_NO_PRESCALER , TIMER0_PRESCALER_8 , TIMER0_PRESCALER_64 , TIMER0_PRESCALER_256 , TIMER0_PRESCALER_1024
#define TIMER0_PRESCALER      TIMER0_PRESCALER_64

#endif
